Sprint2
ClevertecFrontendLab/sprint2-oreshkevich pull request #1
Opened 2023-02-04 21:16 UTC by oreshkevich

![image](https://user-images.githubusercontent.com/68184678/216789868-35b03bb4-7410-45fa-a1fa-afaa4167e1a3.png)
Добрый вечер, что-то не пойму с тестами не проходит 2 он их не видит или еще что 
![image](https://user-images.githubusercontent.com/68184678/216789901-8a13a960-7862-4c51-a41a-0842194691e2.png)

2023-02-04 21:20 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 10.
Количество непройденных тестов: 2.
***
**Test width 1440px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/Test%20width%201440px%20--%20test%20navigation%20view%20(failed).png)
***
**Test width 768px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/Test%20width%20768px%20--%20test%20navigation%20view%20(failed).png)
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675545606/slider%20one%20foto%20768px.png)

2023-02-04 23:40 UTC, SergeyGlazun requested changes

2023-02-04 23:40 UTC, SergeyGlazun commented on .editorconfig
> +root = true
судя по скринам и описанием ошибки у вас начальное положение списка закрытое, сделайте начальное положение списка открытым, также внимательно id

2023-02-05 09:01 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675587695/slider%20one%20foto%20768px.png)

2023-02-05 09:51 UTC, SergeyGlazun requested changes

2023-02-05 09:51 UTC, SergeyGlazun commented on cypress/e2e/sprint2.cy.js
![image](https://user-images.githubusercontent.com/70904466/216811679-0b8bb73f-4ec2-4150-8305-823cae64663e.png)
не закрывается бургер вне окна, ознакомьтесь с требованиями к бургеру)

2023-02-05 09:51 UTC, SergeyGlazun commented on cypress/e2e/sprint2.cy.js
> -    cy.get('[data-test-id=app]').screenshot('slider not foto 1440px', { clip: { x: 0, y: 0, width: 1440, height: 950 } });
![image](https://user-images.githubusercontent.com/70904466/216811736-0bead35d-b4f6-4ff0-be9e-82c91f29bc53.png)
наложение при появлении

2023-02-05 09:51 UTC, SergeyGlazun commented on cypress/e2e/sprint2.cy.js
> +    cy.get('[data-test-id=app]').screenshot('slider not foto 1440px', {
![image](https://user-images.githubusercontent.com/70904466/216811815-ec2f5d11-19bd-4bd0-ac41-4dff3294bfd2.png)

2023-02-05 09:51 UTC, SergeyGlazun commented on cypress/e2e/sprint2.cy.js
> +      clip: { x: 0, y: 0, width: 1440, height: 950 },
![image](https://user-images.githubusercontent.com/70904466/216811892-6418988b-d4ac-4a25-8ae0-73d3ec838013.png)
не выделяется активная книга

2023-02-05 09:51 UTC, SergeyGlazun commented on cypress/e2e/sprint2.cy.js
> +    });
![image](https://user-images.githubusercontent.com/70904466/216812135-34af4158-d542-4547-bf87-814877d0075f.png)
не сворачивается

2023-02-05 09:51 UTC, SergeyGlazun commented on cypress/e2e/sprint2.cy.js
>      cy.visit('http://localhost:3000');
![image](https://user-images.githubusercontent.com/70904466/216812171-01fc2c96-bfb8-41a8-a666-2ea49c0ac493.png)
такой штуки нет в дизайне)

2023-02-05 09:51 UTC, SergeyGlazun commented on cypress/e2e/sprint2.cy.js
>      cy.get('[data-test-id=card]').eq(1).should('be.exist').click();
![image](https://user-images.githubusercontent.com/70904466/216812226-d664d19a-f795-4412-a163-713d5dc4cf40.png)

2023-02-05 12:31 UTC, oreshkevich commented on .editorconfig
> +root = true
Я это исправил

2023-02-05 18:49 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675622959/slider%20one%20foto%20768px.png)

2023-02-05 20:30 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/oreshkevich/1675628999/slider%20one%20foto%20768px.png)

2023-02-05 22:09 UTC, SergeyGlazun requested changes
подправь мелки замечания и можно лить

2023-02-05 22:09 UTC, SergeyGlazun commented on src/components/sidebar/sidebar.jsx
> +                      ? 'sidebar__link active-link'
с работой url в react нужно использовать useParams

2023-02-05 22:09 UTC, SergeyGlazun commented on src/pages/book/book-page.jsx
> +      {/* <Burger onClick={onClick} location={location} clickHideMenu={clickHideMenu} onShow={onShow} /> */}
убирай коменты

2023-02-05 22:09 UTC, SergeyGlazun commented on src/app/app.jsx
>                  />
вернее не по дизайну, поставь границы

2023-02-06 12:39 UTC, oreshkevich commented on src/app/app.jsx
>                  />
исправил

2023-02-06 12:39 UTC, oreshkevich commented on src/components/sidebar/sidebar.jsx
> +                      ? 'sidebar__link active-link'
исправил

2023-02-06 12:39 UTC, oreshkevich commented on src/pages/book/book-page.jsx
> +      {/* <Burger onClick={onClick} location={location} clickHideMenu={clickHideMenu} onShow={onShow} /> */}
исправил

2023-02-06 12:49 UTC, SergeyGlazun approved these changes

2023-02-06 12:52 UTC, merged